/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import bl.Sender;
import bl.SenderTableModel;

/**
 *
 * @author oskar
 */
public class GUI extends javax.swing.JFrame {

    private SenderTableModel bl = new SenderTableModel();
    
    public GUI() {
        initComponents();
        
        RadioTable.setModel(bl);
        RadioTable.setDefaultRenderer(Object.class, new SenderTableRenderer());
        bl.add(new Sender("Kronehit", "FM", 182.3));
        bl.add(new Sender("FM4", "FM", 123.1));
        bl.add(new Sender("Ö3", "AM", 92.3));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMAdd = new javax.swing.JMenuItem();
        jMBandHide = new javax.swing.JMenuItem();
        jMBandShow = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        RadioTable = new javax.swing.JTable();

        jMAdd.setText("hinzufügen");
        jMAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAddActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMAdd);

        jMBandHide.setText("Band verstecken");
        jMBandHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBandHideActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMBandHide);

        jMBandShow.setText("Band anzeigen");
        jMBandShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBandShowActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMBandShow);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setComponentPopupMenu(jPopupMenu1);

        RadioTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(RadioTable);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAddActionPerformed
        SenderDlg dl = new SenderDlg(this,true);
        dl.setVisible(true);
        if(dl.isOk()){
            bl.add(dl.getS());
        }
        
        
    }//GEN-LAST:event_jMAddActionPerformed

    private void jMBandHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBandHideActionPerformed
        bl.updateColBand(false);
    }//GEN-LAST:event_jMBandHideActionPerformed

    private void jMBandShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBandShowActionPerformed
        bl.updateColBand(true);
    }//GEN-LAST:event_jMBandShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RadioTable;
    private javax.swing.JMenuItem jMAdd;
    private javax.swing.JMenuItem jMBandHide;
    private javax.swing.JMenuItem jMBandShow;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
